name: Export

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Pull tags
        run: git fetch --tags --force

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: install pakku
        run: brew install juraj-hrivnak/pakku/pakku

      - name: export pack
        run: pakku export

      - name: Cache MOD Jar
        uses: actions/cache@v4
        with:
          path: |
            build/.cache
          key: ${{ hashFiles("pakku-lock.json") }}

      - name: Rename Packs
        shell: bash
        run: |
          mv build/curseforge/{,CLIENTPACK-}tech-${{ github.ref_name }}.zip
          mv build/serverpack/{,SERVERPACK-}tech-${{ github.ref_name }}.zip

      - name: Release Packs
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/curseforge/CLIENTPACK-tech-${{ github.ref_name }}.zip
            build/serverpack/SERVERPACK-tech-${{ github.ref_name }}.zip
